import { FilmIcon, LightBulbIcon, CameraIcon, SparklesIcon, FaceSmileIcon, RectangleGroupIcon, MaskIcon, PhotoIcon, BookOpenIcon, StoryboardIcon, UserCircleIcon, ViewGridIcon } from './components/icons';
import type { Tool } from './types';

export const TOOLS: Tool[] = [
  { id: 'character-sheet', name: '캐릭터 시트', icon: FilmIcon },
  { id: 'lighting-color', name: '조명/색감', icon: LightBulbIcon },
  { id: 'angle-change', name: '앵글 변경', icon: CameraIcon },
  { id: 'expression-pose', name: '표정/포즈', icon: FaceSmileIcon },
  { id: 'prompt-generator', name: '프롬프트 생성기', icon: SparklesIcon },
  { id: 'cosplay', name: '코스프레', icon: MaskIcon },
  { id: 'background-prop', name: '배경/소품 변경', icon: PhotoIcon },
  { id: 'prompt-library', name: 'Awesome 프롬프트', icon: BookOpenIcon },
  { id: 'story-creator', name: '스토리 생성기', icon: StoryboardIcon },
  { id: 'profile-photo', name: 'AI 프로필 생성', icon: UserCircleIcon },
  { id: 'instagram-grid-poster', name: '인스타 그리드 포스터', icon: ViewGridIcon },
  { id: 'snapshot-generator', name: 'AI 스냅사진 생성기', icon: PhotoIcon },
  { id: 'start-end-frame', name: 'Start/End 생성기', icon: StoryboardIcon },
  { id: 'final-sheet', name: '최종 시트', icon: RectangleGroupIcon },
];

export const CHARACTER_SHEET_VIEWS = [
  { id: 'extreme-closeup', name: '익스트림 클로즈업', prompt: 'Generate an extreme close-up of the character\'s face on a neutral background, maintaining the same style.' },
  { id: 'closeup', name: '클로즈업', prompt: 'Generate a close-up portrait from the chest up of this character on a neutral background, maintaining the same style.' },
  { id: 'front', name: '정면', prompt: 'Generate a full-body, standing, front view of this character on a neutral background, maintaining the same style.' },
  { id: 'back', name: '후면', prompt: 'Generate a full-body, standing, back view of this character on a neutral background, maintaining the same style.' },
  { id: 'left-45', name: '좌 45°', prompt: 'Generate a full-body, standing, 45-degree left-side view of this character on a neutral background, maintaining the same style.' },
  { id: 'left-90', name: '좌 90°', prompt: 'Generate a full-body, standing, 90-degree left profile view of this character on a neutral background, maintaining the same style.' },
  { id: 'right-45', name: '우 45°', prompt: 'Generate a full-body, standing, 45-degree right-side view of this character on a neutral background, maintaining the same style.' },
  { id: 'right-90', name: '우 90°', prompt: 'Generate a full-body, standing, 90-degree right profile view of this character on a neutral background, maintaining the same style.' },
  { id: 'from-above', name: '위에서', prompt: 'Generate a full-body view of this character as seen from above (bird\'s-eye view) on a neutral background, maintaining the same style.' },
  { id: 'from-below', name: '아래에서', prompt: 'Generate a full-body view of this character as seen from below (worm\'s-eye view) on a neutral background, maintaining the same style.' },
];

export const ANGLE_OPTIONS = [
    { id: 'eye-level', name: '눈높이 샷', prompt: 'Generate an image of the subject from an eye-level shot angle.' },
    { id: 'high-angle', name: '하이 앵글 샷', prompt: 'Generate an image of the subject from a high-angle shot.' },
    { id: 'extreme-high-angle', name: '익스트림 하이 앵글 샷', prompt: 'Generate an image of the subject from an extreme high-angle shot.' },
    { id: 'aerial-view', name: '에어리얼 뷰', prompt: 'Generate an image of the subject from an aerial view.' },
    { id: 'aerial-drone', name: '드론 샷', prompt: 'Generate an image of the subject from an aerial drone shot.' },
    { id: 'photo-from-above', name: '탑뷰', prompt: 'Generate a photo of the subject taken from directly above.' },
    { id: 'overhead-shot', name: '오버헤드 샷', prompt: 'Generate an image of the subject from an overhead shot or top view.' },
    { id: 'birds-eye', name: "버즈 아이 뷰", prompt: "Generate an image of the subject from a bird's eye view." },
    { id: 'low-angle', name: '로우 앵글 샷', prompt: 'Generate an image of the subject from a low-angle shot.' },
    { id: 'extreme-low-angle', name: '익스트림 로우 앵글 샷', prompt: 'Generate an image of the subject from an extreme low-angle shot.' },
    { id: 'wide-angle', name: '와이드 앵글 샷', prompt: 'Generate an image of the subject using a wide-angle shot.' },
    { id: 'full-body', name: '전신 샷', prompt: 'Generate a full body shot of the subject.' },
    { id: 'medium-shot', name: '미디엄 샷', prompt: 'Generate a medium shot of the subject, from the waist up.' },
    { id: 'close-up', name: '클로즈업 샷', prompt: 'Generate a close-up shot of the subject\'s face.' },
    { id: 'extreme-close-up', name: '익스트림 클로즈업 샷', prompt: 'Generate an extreme close-up shot, focusing on a specific detail of the subject.' },
    { id: 'detail-shot', name: '디테일 샷', prompt: 'Generate a detail shot, focusing on a small, specific part of the subject.' },
    { id: 'side-angle', name: '측면 샷', prompt: 'Generate a side angle shot of the subject.' },
    { id: 'side-profile', name: '프로필 샷', prompt: 'Generate a side profile shot of the subject.' },
    { id: 'two-shot', name: '투 샷', prompt: 'Generate a two shot, including the main subject and another person.' },
    { id: 'shot-from-behind', name: '백 샷', prompt: 'Generate a shot of the subject taken from behind.' },
    { id: 'ots', name: '오버 더 숄더 샷(OTS)', prompt: 'Generate an over-the-shoulder shot of the subject.' },
    { id: 'pov', name: '1인칭 시점 샷(POV)', prompt: 'Generate a point of view (POV) shot from the subject\'s perspective.' },
    { id: 'tracking-dolly', name: '트래킹 / 달리 샷', prompt: 'Generate an image that looks like a tracking or dolly shot, showing motion.' },
    { id: 'tilted-shot', name: '틸트 샷', prompt: 'Generate a tilted shot of the subject.' },
    { id: 'dutch-angle', name: '더치 앵글 샷', prompt: 'Generate a Dutch angle shot of the subject.' },
    { id: 'diagonal-shot', name: '대각선 샷', prompt: 'Generate a diagonal shot of the subject.' },
    { id: 'off-center-close-up', name: '오프 센터 클로즈업', prompt: 'Generate an off-center close-up shot of the subject.' },
    { id: 'off-center-shot', name: '오프 센터 샷', prompt: 'Generate an off-center shot of the subject.' },
    { id: 'rule-of-thirds', name: '삼분할 샷', prompt: 'Generate a shot of the subject composed using the rule of thirds.' },
    { id: 'silhouette-shot', name: '실루엣 샷', prompt: 'Generate a silhouette shot of the subject against a bright background.' },
    { id: 'candid-shot', name: '캔디드 샷', prompt: 'Generate a candid, unposed shot of the subject.' },
    { id: 'foot-on-pavement', name: '로우 레벨 샷', prompt: 'Generate a "foot on the pavement" style shot, low to the ground and showing movement.' },
    { id: 'underwater-shot', name: '수중 샷', prompt: 'Generate an underwater shot of the subject.' },
];

export const LIGHTING_OPTIONS = [
  { id: 'softbox', name: '소프트박스 조명', prompt: 'Re-light the image with softbox lighting.' },
  { id: 'cinematic', name: '시네마틱 조명', prompt: 'Re-light the image with dramatic, cinematic lighting.' },
  { id: 'moody', name: '무디 조명', prompt: 'Re-light the image with moody, low-key lighting.' },
  { id: 'high-key', name: '하이키 조명', prompt: 'Re-light the image with bright, high-key lighting.' },
  { id: 'low-key', name: '로우키 조명', prompt: 'Re-light the image with dark, low-key lighting.' },
  { id: 'volumetric', name: '볼류메트릭 조명', prompt: 'Add volumetric lighting to the image, showing visible light rays.' },
  { id: 'amber', name: '앰버 컬러 조명', prompt: 'Re-light the image with a warm, amber color cast.' },
  { id: 'crimson', name: '크림슨 컬러 조명', prompt: 'Re-light the image with a deep, crimson red color cast.' },
  { id: 'emerald', name: '에메랄드 컬러 조명', prompt: 'Re-light the image with a rich, emerald green color cast.' },
  { id: 'fuchsia', name: '푸시아 / 바이올렛 조명', prompt: 'Re-light the image with a vibrant fuchsia or violet color cast.' },
  { id: 'b-and-w', name: '흑백 조명', prompt: 'Convert the image to black and white with dramatic contrast.' },
  { id: 'natural', name: '자연광', prompt: 'Re-light the image with soft, natural daylight.' },
  { id: 'golden-hour', name: '골든 아워 조명', prompt: 'Re-light the image with warm, golden hour lighting.' },
  { id: 'blue-hour', name: '블루 아워 조명', prompt: 'Re-light the image with cool, blue hour lighting.' },
  { id: 'backlight', name: '역광 (실루엣)', prompt: 'Re-light the image with a strong backlight to create a silhouette effect.' },
];

export const QUALITY_OPTIONS = [
  { id: 'quality-hdr', name: 'HDR 효과', prompt: 'Dramatically apply a High Dynamic Range (HDR) effect. Make the darks darker and the brights brighter, revealing hidden details in shadows and highlights for a powerful, high-contrast result.' },
  { id: 'quality-sharp', name: '초고화질 선명도', prompt: 'Make this image incredibly sharp and detailed. Enhance all textures, edges, and fine details to the maximum for a hyper-realistic, crisp result.' },
  { id: 'quality-upscale', name: '4K 해상도 업스케일', prompt: 'Upscale this image to 4K resolution. Intelligently add realistic details and textures to make it look like it was shot with a high-end camera. The final image must be sharp and clear.' },
  { id: 'quality-denoise', name: '완벽한 노이즈 제거', prompt: 'Completely remove all digital noise, grain, and compression artifacts. The final image should be perfectly clean and smooth, without looking blurry or losing important texture.' },
  { id: 'quality-vibrant', name: '최대 색감 부스트', prompt: 'Boost the color vibrancy to the maximum. Make every color incredibly rich, saturated, and vivid. The image should pop with life and energy.' },
  { id: 'quality-restore', name: '전문 사진 복원', prompt: 'Professionally restore this photograph. Fix all scratches, dust, and blemishes. Correct color fading and improve overall clarity and sharpness. Make it look brand new.' },
  { id: 'quality-clarity', name: '명료도 극대화', prompt: 'Significantly increase the clarity and local contrast of the image. Make the subject pop from the background and give the image a punchy, defined look.' },
  { id: 'quality-cinematic-grade', name: '시네마틱 컬러 그레이딩', prompt: 'Apply a professional cinematic color grade. Shift the colors towards a teal and orange palette, deepen the shadows, and give it a dramatic, movie-like atmosphere.' },
  { id: 'quality-studio-polish', name: '하이엔드 스튜디오 보정', prompt: 'Give this image a high-end studio polish. Retouch skin to be flawless but natural, even out the lighting for a perfect look, and remove any distracting imperfections.' },
  { id: 'quality-hyper-texture', name: '초현실적 텍스처', prompt: 'Enhance all textures to a hyper-realistic level. Make skin pores, fabric weaves, wood grain, and metal scratches incredibly detailed and tactile.' },
];

export const EXPRESSION_OPTIONS = [
  { id: 'happy', name: '행복', prompt: 'Change the expression to happy, smiling.' },
  { id: 'sad', name: '슬픔', prompt: 'Change the expression to sad, melancholic.' },
  { id: 'angry', name: '분노', prompt: 'Change the expression to angry, furious.' },
  { id: 'surprised', name: '놀람', prompt: 'Change the expression to surprised, shocked.' },
  { id: 'laughing', name: '웃음', prompt: 'Change the expression to laughing joyfully.' },
  { id: 'crying', name: '울음', prompt: 'Change the expression to crying, with tears.' },
  { id: 'winking', name: '윙크', prompt: 'Change the expression to winking playfully.' },
  { id: 'neutral', name: '무표정', prompt: 'Change the expression to neutral, emotionless.' },
  { id: 'disgusted', name: '역겨움', prompt: 'Change the expression to disgusted.' },
  { id: 'fearful', name: '두려움', prompt: 'Change the expression to fearful, scared.' },
];

export const POSE_OPTIONS = [
  { id: 'standing', name: '서 있는 자세', prompt: 'Change the pose to a standard standing position.' },
  { id: 'sitting', name: '앉은 자세', prompt: 'Change the pose to sitting on a chair or stool.' },
  { id: 'walking', name: '걷는 자세', prompt: 'Change the pose to walking forward.' },
  { id: 'running', name: '뛰는 자세', prompt: 'Change the pose to running.' },
  { id: 'jumping', name: '점프하는 자세', prompt: 'Change the pose to jumping in the air.' },
  { id: 'lying-down', name: '누운 자세', prompt: 'Change the pose to lying down on a flat surface.' },
  { id: 'arms-crossed', name: '팔짱 낀 자세', prompt: 'Change the pose to standing with arms crossed.' },
  { id: 'hands-on-hips', name: '손을 허리에 댄 자세', prompt: 'Change the pose to standing with hands on hips.' },
  { id: 'waving', name: '손 흔드는 자세', prompt: 'Change the pose to waving a hand.' },
  { id: 'thinking', name: '생각하는 자세', prompt: 'Change the pose to a thinking posture, perhaps with a hand on the chin.' },
  { id: 'fighting-stance', name: '전투 자세', prompt: 'Change the pose to a dynamic fighting stance.' },
  { id: 'dancing', name: '춤추는 자세', prompt: 'Change the pose to a dancing motion.' },
  { id: 'stretching', name: '스트레칭 자세', prompt: 'Change the pose to stretching, like after waking up.' },
  { id: 'leaning', name: '기댄 자세', prompt: 'Change the pose to leaning against a wall.' },
  { id: 'kneeling', name: '무릎 꿇은 자세', prompt: 'Change the pose to kneeling on one knee.' },
  { id: 'crouching', name: '웅크린 자세', prompt: 'Change the pose to a crouching or squatting position.' },
  { id: 'pointing', name: '가리키는 자세', prompt: 'Change the pose to pointing at something.' },
  { id: 'shrugging', name: '어깨 으쓱하는 자세', prompt: 'Change the pose to shrugging the shoulders.' },
  { id: 'bowing', name: '절하는 자세', prompt: 'Change the pose to bowing respectfully.' },
  { id: 'yoga-pose', name: '요가 자세', prompt: 'Change the pose to a simple yoga pose like the tree pose.' },
];

export const HAIRSTYLE_OPTIONS = [
  { id: 'hair-long-wavy', name: '긴 웨이브 헤어', prompt: 'Change the hairstyle to long, wavy hair.' },
  { id: 'hair-short-bob', name: '숏컷 밥', prompt: 'Change the hairstyle to a short, chic bob cut.' },
  { id: 'hair-ponytail', name: '포니테일', prompt: 'Change the hairstyle to a high ponytail.' },
  { id: 'hair-pixie', name: '픽시컷', prompt: 'Change the hairstyle to a sleek pixie cut.' },
  { id: 'hair-braided', name: '땋은 머리', prompt: 'Change the hairstyle to a braided crown or similar braided style.' },
  { id: 'hair-space-buns', name: '스페이스 번', prompt: 'Change the hairstyle to playful space buns.' },
  { id: 'hair-top-knot', name: '상투머리', prompt: 'Change the hairstyle to a messy top knot with bangs.' },
  { id: 'hair-undercut', name: '언더컷', prompt: 'Change the hairstyle to a stylish undercut.' },
  { id: 'hair-updo', name: '업스타일', prompt: 'Change the hairstyle to an elegant chignon updo.' },
  { id: 'hair-dreads', name: '드레드락', prompt: 'Change the hairstyle to dreadlocks.' },
];

export const CLOTHING_OPTIONS = [
  { id: 'cloth-leather-jacket', name: '가죽 자켓', prompt: 'Change the clothing to a classic black leather jacket.' },
  { id: 'cloth-evening-gown', name: '이브닝 드레스', prompt: 'Change the clothing to an elegant evening gown.' },
  { id: 'cloth-denim-overalls', name: '데님 오버롤', prompt: 'Change the clothing to casual denim overalls.' },
  { id: 'cloth-business-suit', name: '비즈니스 정장', prompt: 'Change the clothing to a professional business suit.' },
  { id: 'cloth-knit-sweater', name: '니트 스웨터', prompt: 'Change the clothing to a cozy oversized knitted sweater.' },
  { id: 'cloth-sci-fi-armor', name: 'SF 갑옷', prompt: 'Change the clothing to sci-fi futuristic armor.' },
  { id: 'cloth-kimono', name: '기모노', prompt: 'Change the clothing to a traditional floral kimono.' },
  { id: 'cloth-maxi-dress', name: '맥시 드레스', prompt: 'Change the clothing to a bohemian maxi dress.' },
  { id: 'cloth-tracksuit', name: '운동복', prompt: 'Change the clothing to a sporty tracksuit and sneakers.' },
  { id: 'cloth-vintage-dress', name: '빈티지 드레스', prompt: 'Change the clothing to a vintage-style dress.' },
];